version: "3.3"

services:
  app:
    image: speechbrain-train:latest
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./clearml.conf:/root/clearml.conf
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all